### ISSUE TITLE
Do not generate graph_app  executable file

### ISSUE THREAD

**Issue by peyer** [XiaoMi/nnlib#1]
Hello, I have compiled hexagon_nnlib after
0) Download and install the Hexagon SDK 3.3 (3.2 may also work)
1) Source the Hexagon SDK setup_sdk_env.sh script.
2) make tree VERBOSE=1 V=hexagon_Release_dynamic_toolv81_v60
3) make tree VERBOSE=1 V=android_Release

However, I did not got graph_app executable file under android_Release/ship. I only got dynamic file

**Comment by liyinhgqw** [comment]
Update the doc. You don't need graph_app.

Please refer to https://mace.readthedocs.io/en/latest/faq.html
