### ISSUE TITLE
is FullyConnected operator missing?

### ISSUE THREAD

**Issue by apivovarov** [XiaoMi/nnlib#13]
I have a question about `FullyConnected` operator.

I found that NNLib has some draft op code in https://github.com/XiaoMi/nnlib/blob/master/hexagon/ops/src/op_fully_connected.c

It has `FullyConnected_u8` op and couple other commented out ops such as `QuantizedFC_8x8p8to8`.

`ops.def` has only `FullyConnected_u8`
https://github.com/XiaoMi/nnlib/blob/master/interface/ops.def#L193

Looks like `FullyConnected_u8` was designed for `uint8` inputs, but I do not see input min/max tensors, weight min/max, bais min/max. So it works with uint8 but non-quantized data??? That is strange.

What about `QuantizedFC_8x8p8to8`? It uses two non existing functions `fc_layer_execute_opt` and `fc_layer_execute_ref`. Another functions are found instead `fc_layer_execute` and `fc_layer_execute_hvx` but they are not used by any operators.

`supported_ops.txt` does not have any info about FullyConnected op.
https://github.com/XiaoMi/nnlib/blob/master/docs/supported_ops.txt

So, what should I do if my model has FullyConnected layer. How to convert it to Hexagon NNLib graph?

**Comment by lee-bin** [comment]
@apivovarov We have not used FC of nnlib before. Maybe you can transform FC to conv1x1 or matmul?

**Comment by apivovarov** [comment]
Great! Thank you for help! 

A bit more info on replacing FullyConnected with Conv2d. https://sebastianraschka.com/faq/docs/fc-to-conv.html

Let me try `OP_QuantizedConv2d_8x8to32` + `OP_QuantizedBiasAdd_32p32to32` + `OP_Requantize_32to8` -  NNLib graph optimizer should be able to convert it to D32 SuperNode, which is blazingly fast.

**Comment by apivovarov** [comment]
I think the following tflite graph uses `conv2d` to replaces `FullyConnected` (1,1,1,7) -> (1,1,1,4)
TFLite kernel format is (OHWI) - (4,1,1,7)
https://pivovaa-us-west-1.s3-us-west-1.amazonaws.com/models/conv2d.html
