### ISSUE TITLE
pmu_adsp.h not found

### ISSUE THREAD

**Issue by dsimmoAnyVision** [XiaoMi/nnlib#2]
Hi. I am currently trying to run the nnlib example, but I encounter the following error

`test/graphmain.c:436:22: fatal error: pmu_adsp.h: No such file or directory #include "pmu_adsp.h" ^ compilation terminated.`

I have searched for the header fileonline, but can't seem to find it:

  1)  Is this something that has been encountered on your system?
  2)  If so, how did you resolve it?

**Comment by yejw5** [comment]
@dsimmo Could you paste the reproduction commands?

**Comment by BingShaw** [comment]
Hi, @dsimmo , Did you solve a problem?

**Comment by BingShaw** [comment]
Hi, @dsimmo have you solved the problem?
