### ISSUE TITLE
这个仓库的用法和相关疑问

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/nnlib#6]
你好，我想问下
1. 这个nnlib是Hexagon DSP SDK的上一层封装，用来打通安卓嘛？底层调用关系的疑问
2. 这个仓库代码是谁来维护的呀，是安卓官方嘛，因为我也看到仓库给了连接https://source.codeaurora.org/quic/hexagon_nn/nnlib，而且我看这个链接里的代码11天前有更新，咱们这边小米的提交是同步更新嘛？
3. 这个nnlib和SNPE dsp/aip runtime与Hexagon DSP SDK，Android NN API的关系？

问题有点多哈，感谢~

**Comment by ysh329** [comment]
4. 咱们这个仓库好像和这个仓库有点像：https://github.com/waau/qualcomm-nnlib，两个一样嘛（用途/功能）

**Comment by lee-bin** [comment]
这个仓库是针对MACE做了部分定制的nnlib，MACE中的Hexagon DSP即是集成了这个。

**Comment by ysh329** [comment]
感谢~
